[tool.poetry]
name = "forma"
version = "0.1.0"
description = ""
authors = ["Linkus, PiGuy"]

[tool.poetry.dependencies]
python = "^3.8"
ply = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
